name: Gold Price Monitor

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ?保证拉取完整 commit 历史，不用只拉取触发 commit

      - name: Print files for debugging
        run: |
          echo "[DEBUG] 当前文件列表:"
          ls -l
          echo "[DEBUG] gold_notice.py 内容:"
          cat gold_notice.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run gold monitor
        env:
          PRICE_UP_THRESHOLD: "0"
          PRICE_DOWN_THRESHOLD: "0"
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: |
          python gold.py
